### ISSUE TITLE
Aelia Foundation Classes

### ISSUE THREAD

**Issue by jasperf** [aelia-co/WooCommerce-Plugin-Template#1]
When will this plugin template be updated including Aelia Foundation Classes? Currently having this error 

```
Notice: The plugin metadata file does not contain the required 'name' and/or 'version' keys. 
in /Users/jasper/code/domain.com/site/web/app/plugins/wc-aelia-foundation-classes/src/vendor/yahnis-elsts/plugin-update-checker/Puc/v4p7/Metadata.php 
on line 42
```

and could use a fix for it.

**Comment by jasperf** [comment]
Found http://bit.ly/WC_AFC_S3 for latest Aelia Foundation Classes version, just not repository yet. And.. error remains it seems.

**Comment by daigo75** [comment]
The Aelia Foundation Classes is a separate plugin, which provides shared libraries to our other plugins. It's meant to be separate from the "consumer" plugins, not embedded in them, so it won't be added to this repository. 

The AFC is not in a public repository, at the moment, but that should not matter much. The notice comes from [the Plugin Update Checker library, by Yahnis Elsts](https://github.com/YahnisElsts/plugin-update-checker). When the response from the update server doesn't contain the information it expects, it shows a notice in PHP, even though that is not needed. 

I submitted a pull request to the original author, to allow suppressing the notice using a filter. The AFC already handles invalid meta, it's not necessary to raise PHP notices.

**Comment by jasperf** [comment]
I see. Well then I can let it be for now. Appreciate the heads up and pull request request.

**Comment by daigo75** [comment]
No bother at all. Actually, I have to thank you for taking the time to report the issue. 👍

All the best, especially in this period of "viral chaos".
